In [1]:
pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

In [14]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,10]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("rank(차원):", x.ndimension())


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
rank(차원): 2


In [6]:
# unsqueeze() : 랭크늘리기
# squeeze(): 텐서 랭크 중 크기 1 랭크 삭제
# view():

SyntaxError: illegal target for annotation (<ipython-input-6-fd3da3b41416>, line 1)

In [8]:
# 랭크 늘리기
# 텐서 첫째 자리에 (0번째)에 1차원 추가 [1, 3, 3] 형태의 3차원 텐서로 변환
# 차원은 늘어나도 텐서 속 원소의 수는 유지

x = torch.unsqueeze(x, 0)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("rank(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
rank(차원): 3


In [9]:
# 랭크 줄이기
# 랭크는 줄어도 텐서 속 원소의 수는 유지
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("rank(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
rank(차원): 2


In [15]:
# 차원의 형태 바꾸기

x = x.view(9)     #1차원 텐서로~~ 텐서 원소 개수 변경은 안됨

print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("rank(차원):", x.ndimension())

tensor([ 1,  2,  3,  4,  5,  6,  7,  8, 10])
Size: torch.Size([9])
Shape: torch.Size([9])
rank(차원): 1


In [16]:
# 원소가 9개인 텐서를 2x4 원소 8개로 변경 안됨 
try:
    x = x.view(2,4)
    except Exception as e:
        print(e)        # 에러 출력

SyntaxError: invalid syntax (<ipython-input-16-5ac1d3d8f8b1>, line 3)

randn(): 인자에서 정한 shape의 정해진 dtype에 따라 무작위 텐서

torch.mm(): 행렬곱

In [18]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print("w size:", w.size())
print("x size:", x.size())
print("w", w)
print("x", x)


w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w tensor([[ 0.3251, -0.7606, -0.2593],
        [ 0.0320,  1.4053, -0.3250],
        [ 0.4165,  0.7218, -0.1875],
        [ 0.1591,  0.3795, -0.6358],
        [-0.4047,  1.2709, -0.7325]])
x tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [20]:
# 행렬 연산 위한 b텐서 설정

b = torch.randn(5, 2, dtype=torch.float)
print("b:", b.size())
print("b:", b)

b: torch.Size([5, 2])
b: tensor([[-0.8485, -0.5631],
        [ 1.5125, -0.3357],
        [ 1.8770, -1.1680],
        [-0.8091,  0.5207],
        [-0.6045,  1.1489]])


In [21]:
# 행렬곱 수행

wx = torch.mm(w,x)  #w의 행은 5, x의 열은 2. 즉 shape은 [5,2] 입니다.
print("wx size:", wx.size())
print("wx:", wx)


wx size: torch.Size([5, 2])
wx: tensor([[-3.2531, -3.9479],
        [ 2.6227,  3.7350],
        [ 1.6440,  2.5947],
        [-1.8818, -1.9791],
        [-0.2544, -0.1206]])


In [22]:
result = wx + b
print("result size:", result.size())
print("result:", result)

result size: torch.Size([5, 2])
result: tensor([[-4.1016, -4.5110],
        [ 4.1352,  3.3993],
        [ 3.5210,  1.4267],
        [-2.6909, -1.4584],
        [-0.8589,  1.0283]])
