# Numpy

Numpy는 수치 해석용 파이썬 패키지다. 리스트에 담긴 데이터를 행렬로 만들어 관리할때 사용한다.
 - 행렬 안에 있는 모든 값은 같은 타입이어야한다.
 - 관리하는 원소의 개수를 변경할 수 없다.

### 패키지 import

In [2]:
import numpy as np

### 1차원 배열/행렬만들기

In [11]:
list1 = [10, 20, 30, 40, 50]
array1 = np.array([10, 20, 30, 40, 50])

print(list1)
print(array1)

print(type(list1))
print(type(array1))

[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'list'>
<class 'numpy.ndarray'>


In [12]:
array1

array([10, 20, 30, 40, 50])

### 벡터 연산

In [7]:
print(list1 * 3)
print(array1 * 3)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 30  60  90 120 150]


In [27]:
print(array1)
print(array1 + 10)
print(array1 * 10)
print(array1 - 10)
print(array1 % 10)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[10 20 30]
 [40 50 60]]
[[-9 -8 -7]
 [-6 -5 -4]]
[[1 2 3]
 [4 5 6]]


In [9]:
list2 =[10, 20, 30, 40, 50]
list3 = [1, 2, 3, 4, 5]
print(list2 + list3)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]


In [13]:
array2 = np.array([10, 20, 30, 40, 50])
array3 = np.array([1, 2, 3, 4, 5])
print(array2 + array3)

[11 22 33 44 55]


In [14]:
print(array2 == 30)

[False False  True False False]


### 2차원 배열 만들기

In [19]:
list1 = [
    [1, 2, 3],
    [4, 5, 6]
]

list1

[[1, 2, 3], [4, 5, 6]]

In [20]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#행의 개수
len(array1)

2

In [23]:
#열의 개수
len(array1[0])

3