In [22]:
import numpy as np

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
print(f'array1의 차원 수: {array1.ndim}')
print(f'array1의 행열 수: {array1.shape}')
print(f'array2의 차원 수: {array2.ndim}')
print(f'array2의 행열 수: {array2.shape}')

array1의 차원 수: 1
array1의 행열 수: (3,)
array2의 차원 수: 2
array2의 행열 수: (2, 3)


### 배열의 인덱싱

In [25]:
list1 = [10, 20, 30, 40, 50]
list2 = [[10, 20, 30], [40, 50, 60]]
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

In [26]:
# 0번째 값을 가지고 온다.
print(list1[0])
print(array1[0])

# 2번째 값을 가지고 온다.
print(list1[2])
print(array1[2])

# -1번째 값을 가지고 온다.
print(list1[-1])
print(array1[-1])

# -3번째 값을 가지고 온다.
print(list1[-3])
print(array1[-3])


10
10
30
30
50
50
30
30


In [27]:
# 0행 0열 값을 가져온다.
print(list2[0][0])
print(array2[0, 0])

# 1행 2열 값을 가져온다.
print(list2[1][2])
print(array2[1, 2])

# 마지막행 마지막열 값을 가져온다.
print(list2[-1][-1])
print(array2[-1, -1])

10
10
60
60
60
60


In [28]:
# array1에서 20의 배수만 가져온다.

# 전체를 가져온다.
print(array1)

# 20의 배수인지 확인한다.
print(array1 % 20)

[10 20 30 40 50]
[10  0 10  0 10]


In [29]:
# True, False를 이용한 값 가져오기
# []안에 True와 False가 값인 행렬을 넣어주면 True 자리에 해당하는 값만 가져온다.
array3 = np.array([True, False, True, False, True])
print(array1[array3])

[10 30 50]


In [30]:
array4 = np.array([[True, False, True], [False, True, False]])
print(array2[array4])

[10 30 50]


In [31]:
# array1에서 20보다 큰 값만 가져온다.
print(array1)
print(array1 > 20)
print(array1[array1 > 20])

[10 20 30 40 50]
[False False  True  True  True]
[30 40 50]


### 배열 슬라이싱

In [32]:
list1 = [10, 20, 30, 40, 50]
list2 = [[10, 20, 30], [40, 50, 60]]
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

In [38]:
# 일부만 가져온다.
# 시작인덱스 : 끝인덱스 -1
# print(list1[1:4])
# print(list2[0:1], [0:1])

SyntaxError: invalid syntax (<ipython-input-38-18661a832d38>, line 4)

In [41]:
list1 = [10, 11.11, True, '안녕하세요']
array1 = np.array([10, 11.11, True, '안녕하세요'])
print(list1)
print(array1)

[10, 11.11, True, '안녕하세요']
['10' '11.11' 'True' '안녕하세요']


In [42]:
# 0으로 채워진 행렬을 생성한다.
array2 = np.zeros(5)
array2

array([0., 0., 0., 0., 0.])

In [43]:
array3 = np.zeros([2,3])
array3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
array5 = np.ones([2,3], dtype= 'i')
array5

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [45]:
# 쓰레기 값이 담긴 행렬 생성
array6 = np.empty([2,3])
array6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# 범위 값을 가지고 있는 행렬 생성
# 0 ~ 10 -1

array7= np.arange(10)
print(array7)

# 3 ~ 12 -1

array8= np.arange(3, 12)
print(array8)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11]


In [51]:
# 특정 범위 안에서 원하는 만큼의 숫자를 추출해 행열로 생성한다.
# 시작값, 끝 값, 개수

array10 = np.linspace(0, 100, 5)
print(array10)

[  0.  25.  50.  75. 100.]


### 전치 연산 (행과 열을 바꾼다

In [53]:
array1 = np. array([[10, 20, 30], [40, 50, 60]])
array2 = array1.T

print(array1)
print(array2)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


### 배열의 크기 변형

In [58]:
array1 = np.arange(12)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [60]:
array2 = array1.reshape(3, 4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# 행열을 배열로 만든다.
array3 = array2.flatten()
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])